### ISSUE TITLE
有个大胆的想法，把nuclei的也集成进来是不是效果更好

### ISSUE THREAD

**Issue by Zther0** [zema1/yarx#9]
https://github.com/projectdiscovery/nuclei-templates

**Comment by zema1** [comment]
我个人不太喜欢 nuclei 的写法，感觉文档定义太多，学习成本很高。可以换种思路，写一个从 nuclei 到 xray 的转换工具，我这有小伙伴已经初步做了一版，加载 nuclei 转换过来的脚本后大概能单端口扫这么多，不过这个转换工具估计不太能开源。

![nuclei-convert](https://user-images.githubusercontent.com/20637881/143771575-be7ea6b5-95ba-40df-8f97-0b1b032153ab.jpg)
